### ISSUE TITLE
Biology => Footnote format issue

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1677] opened 2018-06-29 09:43 UTC
**Where**: devb & Katalyst01, Biology 1e & 2e books, 11.1 The Process of Meiosis . 
[updated Katalyst01 link below]

**Description**: On the bottom of the page, in footnotes, first note is below it's number.

![image](https://user-images.githubusercontent.com/40228918/42084779-f35b3636-7b8e-11e8-9a0d-3be43ea1c73c.png)

**Comment by PiotrKozlowski** [comment] 2018-07-02 06:59
```
.footnote-ref-content p{
  display: inline-block;
}
```

I think it's also problem with CNXML > HTML conversion, because first list item is inside `<p>` and second isn't.

**Comment by helenemccarron** [comment] 2018-07-03 13:52
@openstaxalina this looks like it might be a content issue, could you double check the markup is correct?

**Comment by openstaxalina** [comment] 2018-07-03 20:33
@Bkblodget could you please check the markup on this?  It's biology (1e) on devb - link above.

**Comment by openstaxalina** [comment] 2018-07-20 21:04
Confirmed this issue is still present with refreshed content: https://katalyst01.cnx.org/contents/jVCgr5SL@8.197:WzgNHpon@3/111-The-Process-of-Meiosis

![screen shot 2018-07-20 at 4 03 41 pm](https://user-images.githubusercontent.com/7863733/43025236-88d9db6a-8c36-11e8-9cac-98981518cc0f.png)

**Comment by openstaxalina** [comment] 2018-07-20 21:06
If it needs to be fixed, this issue should be fixed on production: https://cnx.org/contents/jVCgr5SL@8.18:WzgNHpon@3/The-Process-of-Meiosis

![screen shot 2018-07-20 at 4 05 32 pm](https://user-images.githubusercontent.com/7863733/43025309-d8225b5c-8c36-11e8-96b9-fcdd29fbde3c.png)

**Comment by lwtchu** [comment] 2018-07-23 18:14
Per this issue: https://github.com/Connexions/oer.exports/issues/3350 it might be because a `<para>` is being used. Need to test

**Comment by Bkblodget** [comment] 2018-07-31 20:44
confirmed this error was happening because of a <para> within the <footnote> tag. Once <para> is removed, the footnotes appear correctly. 

<img width="1247" alt="screen shot 2018-07-31 at 3 41 50 pm" src="https://user-images.githubusercontent.com/11299035/43486106-8c89bd16-94d8-11e8-937c-08f017331aef.png">
 
This change has been implemented on prod for chapter 11 section 1 as well.

**Closed by Bkblodget** 2018-07-31 20:44 UTC
Labels: book:biology, code: content
