### ISSUE TITLE
Improper text wrapping around exercise figures

### ISSUE THREAD

**Issue by lwtchu** [Connexions/webview#1636] opened 2018-05-31 21:55 UTC
https://github.com/Connexions/cnx-recipes/issues/388

Question text wraps incorrectly in some exercises that start with images:

---

![screen shot 2018-05-04 at 3 21 02 pm](https://user-images.githubusercontent.com/28710954/39650856-61a2246c-4faf-11e8-9678-827061a2287a.png)
---
![screen shot 2018-05-04 at 3 20 48 pm](https://user-images.githubusercontent.com/28710954/39650857-61afbb18-4faf-11e8-98e4-d542fccf7194.png)

Book: AP Biology

**Comment by PatBoj** [comment] 2018-07-03 14:48
Fix it
![image](https://user-images.githubusercontent.com/20907906/42227057-e58224c0-7ee0-11e8-9dc0-6144b0788eab.png)

**Comment by wilkus27** [comment] 2018-07-06 08:49
Verified on devb https://devb.cnx.org/contents/bDIuMp-w@5.1:w3qFD6Qv@5.1/Critical-Thinking-Questions:

![images_text](https://user-images.githubusercontent.com/40228854/42369406-2a7062e2-810a-11e8-96a4-3ac713ad6bb4.JPG)

**Comment by wilkus27** [comment] 2018-07-06 09:07
But the problem is still occuring with images of bigger size:
![images_text2](https://user-images.githubusercontent.com/40228854/42370275-9dac3dc4-810c-11e8-83a6-70599a067f33.JPG)

**Comment by PatBoj** [comment] 2018-07-06 11:49
Maybe it could be fixed in recipes? I think we need `if` statement. If the picture would be too big then the content will go to the next line. What do you thnik @helenemccarron?

**Comment by Adrianltd** [comment] 2018-07-06 14:38
Or you can remove `float: left;` and style the text paragraphs wherever they're inline to be block and display below image.

**Comment by openstaxalina** [comment] 2018-07-07 00:54
OpenStax will discuss Monday July 9; will share feedback on July 10 at the latest.

**Comment by openstaxalina** [comment] 2018-07-09 17:52
For now, let's simply make sure that the content is breaking after images.  We will not have text wrapping around images for our minimum viable product.  We can investigate this further in the future.

**Comment by PatBoj** [comment] 2018-07-13 08:54
![image](https://user-images.githubusercontent.com/20907906/42682535-25fd8ca4-868b-11e8-82f2-9b085668fade.png)

![image](https://user-images.githubusercontent.com/20907906/42682539-288b4d08-868b-11e8-9fa3-b8d6e83a1c65.png)

**Comment by openstaxalina** [comment] 2018-07-19 14:52
This is good as-is.  @wilkus27 @Stackblocks please include all EOC images in your testing for this.  Please take a screenshot if this treatment does not work for any particular cases.

**Comment by Stackblocks** [comment] 2018-07-19 14:58
A good source to check would be https://staging.cnx.org/contents/eg-XcBxE@10.1:Qb9bMPxY@10.1/Chapter-Review, where there are a fair number of examples to test. 

![image](https://user-images.githubusercontent.com/12678235/42950737-4a0ce172-8b3a-11e8-81d3-89e1d8137055.png)

**Comment by PatBoj** [comment] 2018-07-26 07:56
@Stackblocks It looks good on my localhost. On staging server my newest changes were not included.
![image](https://user-images.githubusercontent.com/20907906/43249086-0bde70ca-90ba-11e8-8d69-e4e8c5cb0fb4.png)

**Comment by openstaxalina** [comment] 2018-07-26 14:15
@Stackblocks to provide a link to the equivalent content on katalyst01 - chapter 10 chapter review questions.

**Comment by Stackblocks** [comment] 2018-07-26 14:17
Here is the link to the content on Katalyst01: https://cnx.org/contents/eg-XcBxE@9.9:Qb9bMPxY@9.9/Chapter-Review

The fix won't show up on staging until it is part of the release candidate, so the order of checking is localhost -> katalyst01 -> staging (OpenStax deploys after code freeze) -> production.

**Comment by uskka** [comment] 2018-07-27 11:46
Issue fixed on katalyst01. 

![screenshot-katalyst01 cnx org-2018 07 27-13-35-48](https://user-images.githubusercontent.com/40228918/43318700-0195ee48-91a2-11e8-9a93-3779a87a1b00.png)

**Comment by PatBoj** [comment] 2018-08-02 07:37
This issue should be fixed in recipes and webview. I've already done half the job https://github.com/Connexions/cnx-recipes/issues/454/

**Comment by PatBoj** [comment] 2018-08-02 09:32
Fixed :taco: 
![Uploading image.png…]()

**Comment by openstaxalina** [comment] 2018-08-08 16:12
@PatBoj I noticed that the text for exercise 25 drops to the next line in your "After" screenshot, even though there is no image there.  I do not think the text should be on the next line if there is no image.  Is this being resolved via a different issue?

**Comment by PatBoj** [comment] 2018-08-09 07:39
@openstaxalina sorry, my bad, wrong order of screenshots :laughing:. I've already edited my previous comment, everything should be good now.

**Comment by wilkus27** [comment] 2018-08-10 12:12
Verified on katalyst01:

![test2](https://user-images.githubusercontent.com/40228854/43957192-48424cb4-9ca7-11e8-934f-b5ff8aa94848.JPG)

**Closed by wilkus27** 2018-08-10 12:12 UTC
Labels: book:ap.biology, code:CSS, prio:high
