### ISSUE TITLE
Additional Learning Objectives in Introduction 

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#2135] opened 2018-12-13 11:23 UTC
On katalyst01 (https://katalyst01.cnx.org/contents/W8wOWXNF@18.8:ZxUeqvJc@4/Introduction) in Introduction there is extra abstract **Learning Objectives**:

![learn_obj](https://user-images.githubusercontent.com/40228854/49935590-b69a8500-fed1-11e8-9745-e4b911717876.JPG)

PDF:

![learn_obj_pdf](https://user-images.githubusercontent.com/40228854/49935596-bdc19300-fed1-11e8-9b10-05392d7b6885.JPG)

This is only one place, where that problem occurs.

**Comment by PatBoj** [comment] 2018-12-13 11:42
In my opinion it's content issue. Screens below are from raw (not baked) html file:

![image](https://user-images.githubusercontent.com/20907906/49936018-00379f80-fed3-11e8-8657-8b913ddf18eb.png)

![image](https://user-images.githubusercontent.com/20907906/49936020-03329000-fed3-11e8-983a-aa2b31f59a7f.png)

![image](https://user-images.githubusercontent.com/20907906/49936025-06c61700-fed3-11e8-8730-ad0827bf85db.png)

**Comment by openstaxalina** [comment] 2018-12-14 21:15
Since this only occurs in one place, I agree this is a content issue **specific to the chapter 2 introduction module in American Government**.  I am moving this to the content-managers repo.

**Comment by openstaxalina** [comment] 2018-12-14 21:15
Issue moved to [Connexions/content-managers #506](https://github.com/Connexions/content-managers/issues/506) via [**ZenHub**](https://www.zenhub.com/)

**Closed by openstaxalina** 2018-12-14 21:15 UTC
Labels: book:american.government

**Comment by openstaxalina** [comment] 2019-02-13 16:58
Confirmed issue was fixed in content and appears correctly on production:
<img width="1271" alt="screen shot 2019-02-13 at 10 57 58 am" src="https://user-images.githubusercontent.com/7863733/52729163-4914de80-2f7e-11e9-86f9-22f87d7dda7a.png">
