### ISSUE TITLE
Revert button deletes content when draft is saved.

### ISSUE THREAD

**Issue by dcwill** [Connexions/webview#1062] opened 2015-05-04 17:20 UTC
In beta.cnx.org I created a derived copy (I think it may actually be a new draft of an existing collection owned by user dcwill) of the collection: http://beta.cnx.org/contents/1c030cbe-d949-48f1-b338-43cfa84e11bc@draft:1/Perception_of_Music

I went into the first module and clicked "edit page".

Made a small edit... just putting in a space.

Then I clicked "revert".

Then I clicked "save draft"

Then I went back to "my Workspace"

Then I clicked on the page that I had editing and then reverted.

When I clicked this all content below the media element Figure 2 was missing.

![screen shot 2015-05-04 at 12 19 34 pm](https://cloud.githubusercontent.com/assets/1007313/7458157/def430e4-f257-11e4-8f08-7076c2275f69.png)

**Comment by amberwebb** [comment] 2015-05-04 17:37
@dcwill I am trying to reproduce this. I have derived a copy of this content. What page is this happening on? What browser are you using?

**Comment by amberwebb** [comment] 2015-05-27 11:28
Could not reproduce this. The revert button has been removed. Closing this issue.

**Closed by amberwebb** 2015-05-27 11:28 UTC
