### ISSUE TITLE
Author of books listed as "OpenStax College"

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1990] opened 2018-10-19 20:53 UTC
# Scenario
Our book and page author is listed as "OpenStax College" on our books. This should be changed to "OpenStax," as the "OpenStax College" brand no longer exists and can cause confusion.

# Steps to Reproduce

* **Product**: [ ] Tutor   [ ] Concept Coach [ ] OS Web [ ] Content Production Toolkit [ ] CNX

* **How many times were you able to reproduce the issue?** 

* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)

# Environment:

* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

**Comment by openstaxalina** [comment] 2018-11-01 14:47
Examples: https://cnx.org/contents/p7ovuIkl@6.13:udlNhu-X@10/The-Americas, https://cnx.org/contents/Sr8Ev5Og@9.30:-JmAXPOj@6/What-Is-Psychology

**Comment by openstaxalina** [comment] 2018-11-02 14:41
Per Ross, we should perform the following:
1. Login to the OpenStaxCollege account on legacy-staging.cnx.org
2. Change the name to something random (not OpenStax, not OpenStax College)
3. Save
4. Change the name back to "OpenStax"
5. Save
6. Ask Ross to check the staging database to see if the name "OpenStax" shows up for the user "OpenStaxCollege"
7. If this works, I think we just need to do steps 1-5 on Production.

**Comment by reedstrm** [comment] 2018-11-02 15:44
ok looks like it did _not_ work, so to fix this will need more debugging of the user sync code in legacy.

**Comment by omehes** [comment] 2018-11-06 19:40
Adding this staging.cnx.org case to this issue as it is related:

Steps:
1. log in to legacy
2. change your first name (also in Full Name)
3. save and log out
4. log back in to legacy
Expected: the change to your name should still be there
Actual: change is reflected in legacy
5. Now, check webview for one of the collections for that user
Expected: the change in name should be reflected
Actual: changed name does not show

**Comment by openstaxalina** [comment] 2018-12-03 16:47
Duplicate of https://github.com/Connexions/webview/issues/2081, closing.

**Closed by openstaxalina** 2018-12-03 16:47 UTC
Labels: type:bug
