### ISSUE TITLE
Problem with Filter in Search

### ISSUE THREAD

**Issue by uskka** [Connexions/webview#1703] opened 2018-07-09 13:36 UTC
Description: Filter bar is too close to the footer while loading which looks like something broke. 

Where: Cnx/devb. 
https://cnx.org/search?q=subject:%22Arts%22

![screenshot-cnx org-2018 07 09-15-15-59](https://user-images.githubusercontent.com/40228918/42453664-b855be92-838d-11e8-8137-71084f8e3791.png)

**Comment by helenemccarron** [comment] 2018-07-09 15:56
@openstaxalina is this within AW's scope?

**Comment by openstaxalina** [comment] 2018-07-09 22:03
@helenemccarron this is not within AW's scope, but I will keep this in our general backlog.

**Comment by PiotrKozlowski** [comment] 2018-07-27 09:54
Should we make this look like this while loading?
![image](https://user-images.githubusercontent.com/31478212/43314610-b861e366-9193-11e8-9f51-2177f0ebcc89.png)

**Comment by openstaxalina** [comment] 2018-08-07 01:58
@PiotrKozlowski are you planning to work on this for the current release (petty.pegasus)?  It would be helpful to discuss the issues that you are working on on the Thursday call.

**Comment by PiotrKozlowski** [comment] 2018-08-07 08:59
@openstaxalina I already created PR with screenshot how it looks after changes. Of course we can still talk about it.

**Comment by openstaxalina** [comment] 2018-08-16 15:19
Sliding to q.q. milestone since we did not get to discuss this before code freeze for p.p cc @PiotrKozlowski

**Comment by PiotrKozlowski** [comment] 2018-08-16 17:05
@Stackblocks , @kerwinso This is already merged to #1816 (petty.pegasus). Can you test it thoroughly during regression testing?

Plan:
When searching for something (normal or advanced search):
  - progress bar should be centered
  - left, grey column should not be visable
Screenshot: https://github.com/Connexions/webview/issues/1703#issuecomment-408371575

**Comment by openstaxalina** [comment] 2018-08-16 17:14
Thanks, @PiotrKozlowski - I moved this back to petty.pegasus.  cc @helenemccarron

**Comment by Stackblocks** [comment] 2018-08-16 17:18
In the future we should be sure to try and plan things so we can make sure the testing is completed during the functional verification window, because feature testing during a regression testing is bad practice because chews up regression testing time by having to redeploy one or more times.

**Comment by Stackblocks** [comment] 2018-08-16 20:04
Displaying as specified with updated version of content / code.

![2018-08-16_15-02-24.gif](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/da052cba-efa9-4058-a316-da54387cd59d)

**Closed by Stackblocks** 2018-08-16 20:04 UTC
Labels: prio:low, question:Alina
