### ISSUE TITLE
Weighted Search

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/webview#1779] opened 2018-08-01 16:09 UTC
1. Adjust weights in tsearch vectors based on the location (in title, keywords or text) a specific lexeme appears so that the modified search will generate results in the similar order as the existing search.
2. Use the search indices in latest_modules to filter the results.

https://github.com/Connexions/cnx-archive/pull/569

https://github.com/Connexions/cnx-db/pull/132

**Comment by kerwinso** [comment] 2018-08-01 21:31
@CecileJiaqiWang Please add a test plan to this issue, and also link to PRs.

**Comment by kerwinso** [comment] 2018-08-02 15:38
Test plan in Trello

**Comment by kerwinso** [comment] 2018-08-02 19:13
Issue moved to [Connexions/cnx-db #136](https://github.com/Connexions/cnx-db/issues/136) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kerwinso** [comment] 2018-08-02 21:26
Reopening to track this since cnx-db milestone functionality in github is screwed up.

**Comment by kerwinso** [comment] 2018-08-16 14:47
This is a duplicate of https://github.com/Connexions/cnx-db/issues/136. We should track the work in the other issue, not this one. This issue had been temporarily re-opened because the other one in cnx-db was not able to be assigned a milestone due to a bug in Zenhub. This has since been resolved, so we are using https://github.com/Connexions/cnx-db/issues/136 to track work now, not this issue.

Closing this issue.

**Closed by kerwinso** 2018-08-16 14:47 UTC
Labels: rc:demo
