### ISSUE TITLE
Spacing, text alignment is inconsistent in tables

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1655] opened 2018-06-01 16:25 UTC
@hwangange commented on [Mon May 21 2018](https://github.com/Connexions/cnx-recipes/issues/399)

There are multiple instances (beyond the ones listed below) of the inconsistent use of "equations" and plain text in the same column, leading to lack of alignment.

Example of spacing being off: 
<img width="630" alt="screen shot 2018-05-21 at 3 20 11 pm" src="https://user-images.githubusercontent.com/12180288/40328026-877a2e2e-5d0a-11e8-8a99-daf52cbc019e.png">

1.2: Physical Quantities and Units

The additional "(=1)" appears on a new line; additionally, it isn't horizontally centered. At the very least, maybe write it as an equation instead of just plain text?

---------------------------------------

Example of text alignment being off:

<img width="924" alt="screen shot 2018-05-21 at 4 12 10 pm" src="https://user-images.githubusercontent.com/12180288/40330169-c1ca2afa-5d11-11e8-8590-4e27ce64a6e1.png">

5.1: Friction

Might look better if the labels ("Static Friction", "Kinetic Friction"), mu symbols, AND decimals are horizontally centered. 

There are plenty of other instances where cells containing column labels align the text to the left but the rest of the cells in the table are horizontally centered ----> inconsistent alignment of text.

Here's another instance. 

<img width="867" alt="screen shot 2018-05-21 at 4 21 12 pm" src="https://user-images.githubusercontent.com/12180288/40330588-06c866f2-5d13-11e8-98d8-48ec46ef30dd.png">

6.1 Rotation Angle and Angular Velocity

"Degree Measure" and "Radian Measure" are aligned left, but the rest of the cells are horizontally centered.

**Comment by Adrianltd** [comment] 2018-06-19 20:56
@marcjeannott It looks like the alignment issue is caused by the combination of math and plain text. Is that possible to move the (=1) to the math?

**Comment by Adrianltd** [comment] 2018-06-19 21:09
Alignment in 5.1 is already fixed in baked book
![image](https://user-images.githubusercontent.com/40228907/41624345-b4232544-7415-11e8-9e92-a11c682dcd09.png)

**Comment by Adrianltd** [comment] 2018-06-19 21:11
And the same in 6.1 
![image](https://user-images.githubusercontent.com/40228907/41624458-0c4dcb98-7416-11e8-968e-daaf2c9a4347.png)

**Closed as completed** 2018-06-29 16:26 UTC
Labels: book:ap.physics, code:CSS
