### ISSUE TITLE
Issue with math symbols in tables

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/webview#1801] opened 2018-08-03 15:16 UTC
@uskka commented on [Thu Aug 02 2018](https://github.com/Connexions/cnx-recipes/issues/518)

Description: Math symbols in tables are centred and have a big padding while the rest of the content is not centred which makes the tables to look like something broke. 

Where: katalyst01 / College Physics / Useful Information
https://katalyst01.cnx.org/contents/Ax2o07Ul@11.32:cjQyhWg-@7/Useful-Information

![screenshot-katalyst01 cnx org-2018 08 02-12-37-22](https://user-images.githubusercontent.com/40228918/43579383-3887e3f2-9652-11e8-9d34-1f7fdd46dba1.png)
![screenshot-katalyst01 cnx org-2018 08 02-12-59-47](https://user-images.githubusercontent.com/40228918/43579930-f38ccce8-9653-11e8-8bbe-02318bd0aa44.png)

**Comment by openstaxalina** [comment] 2018-08-07 01:45
duplicate of #1802 - closing.

**Closed by openstaxalina** 2018-08-07 01:45 UTC
