### ISSUE TITLE
Double header in Using the Calculator box

### ISSUE THREAD

**Issue by wilkus27** [Connexions/webview#1872] opened 2018-08-24 14:11 UTC
katalyst01(https://katalyst01.cnx.org/contents/MBiUQmmY@20.1:epKVS0wt@12/9-5-Additional-Information-and-Full-Hypothesis-Test-Examples -> **Try It 9.14**)

![double](https://user-images.githubusercontent.com/40228854/44589173-1d2b5400-a7b8-11e8-947f-53b3a49d9b4b.JPG)

PDF: 

![double_pdf](https://user-images.githubusercontent.com/40228854/44589183-26b4bc00-a7b8-11e8-8263-8187f205a275.JPG)

**Comment by Adrianltd** [comment] 2018-08-24 15:53
Rebaked book and it should work. Probably one of the latest PRs has fixed also this one. Assigned @wilkus27 to confirm.

**Comment by wilkus27** [comment] 2018-08-24 16:01
That's right, after baking it is working properly:

![one_head](https://user-images.githubusercontent.com/40228854/44594827-8d8da180-a7c7-11e8-9536-c68b3bb8d12a.JPG)

**Comment by wilkus27** [comment] 2018-08-29 13:43
Reopen, after last baking/deploying problem occurs again.

**Comment by Adrianltd** [comment] 2018-08-29 15:46
@helenemccarron on Friday I baked the stats book on the server and this issue disappeared. After the weekend the book was rebaked by someone else. Can those differences be caused by me having different endpoints in `books.txt`? Should we change all of the endpoints to `katalyst01` in `books.txt`?
https://github.com/Connexions/cnx-recipes/pull/582 and merging this one would probably fix the issue. That's the only difference I can spot in my local files that worked on Friday.

**Comment by helenemccarron** [comment] 2018-08-29 19:12
That shouldn't make a difference since we are using the recipe that's on the server (the current version depends on the branch on the server). I would try to bake it locally to see if the problem exists then make sure the same branch is pulled on the server and try again with the same recipe.

**Comment by Adrianltd** [comment] 2018-09-05 08:27
Moving this issue to cnx-recipes repository.

**Comment by Adrianltd** [comment] 2018-09-05 08:27
Issue moved to [Connexions/cnx-recipes #593](https://github.com/Connexions/cnx-recipes/issues/593) via [**ZenHub**](https://www.zenhub.com/)

**Closed by Adrianltd** 2018-09-05 08:27 UTC
Labels: book:intro.statistics, prio:moderate
