### ISSUE TITLE
Derived Copy - images disappear when Page is derived in collection

### ISSUE THREAD

**Issue by edwoodward** [Connexions/webview#915] opened 2015-02-20 19:58 UTC
I derived a copy of Understanding Basic Music Theory and then derived the Page called The Staff. Before I derived it, there were several images displayed.  Once I derived it, the images did not display in the editor. The happened on beta and dev.

**Comment by amberwebb** [comment] 2015-02-24 17:45
@reedstrm @edwoodward Not sure if this is a webview issue. When a page with images is derived on dev and beta, getting a 404 for dev.cnx.org/resources and beta.cnx.org/resources.

**Comment by edwoodward** [comment] 2015-02-24 18:09
I created an issue for that last week. I'm not sure of the cause.

**Comment by pumazi** [comment] 2015-02-24 18:20
I'm seeing this locally as well.

**Comment by amberwebb** [comment] 2015-02-24 18:21
@pumazi I don't see it locally. Only on dev and beta. It works on demo.

**Comment by pumazi** [comment] 2015-02-24 20:25
@amberwebb Looks like I need to clarify. My issue my be unrelated. I'm not seeing the image, because it looks to be shifted far to the right. So my comment has no, relation to this issue.

**Comment by rich-hart** [comment] 2015-03-12 17:42
This seems to be an issue with the current instance of cnx-authoring running on dev.cnx.org.   When a page is being derived, the image resource hash string is being changed when it is sent to the editor.  For example the image http://dev.cnx.org/resources/db2be0305f84bc13c2e3ff04639b8270 in the original page is being changed to http://dev.cnx.org/resources/68651684a49cebfde8ffc3f76a33a8184cdfdc63  in the derived page, the hash strings should be the same.  This seems to only be a bug in dev at the moment because I've tested it on my own local instance and beta and the image rendered without any problems.

**Comment by amberwebb** [comment] 2015-03-13 15:13
I have derived a copy of Understanding Basic Music Theory on both beta and dev. I can confirm that on both images appeared in the editor. Closing this issue.

**Closed by amberwebb** 2015-03-13 15:13 UTC
Labels: bug, editor, High Priority
