### ISSUE TITLE
Unable to download PDF before and after donating

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1874] opened 2018-08-27 15:54 UTC
#Scenario
We have had multiple users say they are unable to download PDFs before or after donating the $10. The reported issues have been mostly on Safari and Edge. It appears that the Download PDF link is unresponsive. 

Case #25859 Principles of Economics, #25649 College Algebra, #25410 Concepts of Bio, #25291 Chemistry Atoms first

#Steps to Reproduce

* **Product**: [ ] Tutor   [ ] Concept Coach [ ] OS Web [ ] Content Production Toolkit [ x] CNX

* **How many times were you able to reproduce the issue?** 

* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)

#Environment:

* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

#Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

#Next Steps for User
If the card is accepted or rejected, what does user need to know now?

**Comment by philschatz** [comment] 2018-08-27 16:16
It appears to be a CORS issue (deployment fix). The Safari console says this when the page loads:

![image](https://user-images.githubusercontent.com/253202/44671160-53501a00-a9ea-11e8-9631-598a05c6aed5.png)

```
[Error] Origin https://cnx.org is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin https://cnx.org is not allowed by Access-Control-Allow-Origin. (caa57dab-41c7-455e-bd6f-f443cda5519c@13.1:a652edf4-562b-4629-a940-7fc35e8a3727@6, line 0)
[Error] XMLHttpRequest cannot load https://archive.cnx.org/extras/caa57dab-41c7-455e-bd6f-f443cda5519c@13.1:a652edf4-562b-4629-a940-7fc35e8a3727@6 due to access control checks.
[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (9b08c294-057f-4201-9f48-5d6ad992740d@8.1:9d4f1093-3c28-443e-b771-dbe514ae3e5d@6.json, line 0)
```

### Why CORS? / Background Investigation

I tried adding the following link to different parts of the page (thinking that maybe it was a JavaScript click handler eating the click event) but that did not work:

![image](https://user-images.githubusercontent.com/253202/44670986-d2911e00-a9e9-11e8-9a6f-531a505bafc6.png)

`<a class="btn btn-primary" href="/exports/9b08c294-057f-4201-9f48-5d6ad992740d@8.1.pdf/college-algebra-8.1.pdf" data-l10n-id="donation-download-for-free">Download for Free</a>`

When I change the link `href` to point to `https://philschatz.com/...` then the link works.

/cc @reedstrm @Dantemss to help fix the deploy script

**Comment by philschatz** [comment] 2018-08-27 18:40
@reedstrm pointed out the problem is that we *were* closing connections (before the recent deploy to production) but now we’re keeping more of them open (to send more HTTP responses to users) but students are starting classes so we were hitting the default max number of connections to keep open (2000). The next step is to explicitly set the max number of connections to something larger than 2000 (like 5k)

This should fix the PDF link not showing up (the PDF download link makes an AJAX request before enabling the link & it was timing out)

**Comment by kerwinso** [comment] 2018-08-28 22:07
Addressed in 2 PRs:
https://github.com/Connexions/cnx-deploy/pull/758 (maxconn)
https://github.com/Connexions/webview/pull/1876 (Edge & Safari fix)

Scheduled hotfix: 8/29/18

**Closed** 2018-08-29 19:02 UTC
Labels: prio:high
