### ISSUE TITLE
Runaway regexp in content

### ISSUE THREAD

**Issue by RoyEJohnson** [Connexions/webview#1245] opened 2015-11-19 22:04 UTC
To recreate, go here:
http://dev.cnx.org/contents/AgQDEnLI@5.1:Q7ShLma2@3/Theoretical-Perspectives-on-Ed
Open your console
Go to the previous page

`SyntaxError: Invalid regular expression: /^.nea.org/home/40991.htm (http://www.nea.org/home/40991.htm/: Unterminated group(…)`

Navigating away and back will get the same error twice more. Then three more, etc.

**Comment by edwoodward** [comment] 2017-06-08 21:16
Cannot reproduce. Closing.

**Closed by edwoodward** 2017-06-08 21:16 UTC
