### ISSUE TITLE
Baked Books No Longer Landing on First Intro Module

### ISSUE THREAD

**Issue by openstaxalina** [Connexions/webview#1897] opened 2018-09-04 21:12 UTC
We have some code in webview so that when a user navigates to a book, they land on the first module after the preface, aka the first introduction module.

Demonstrated here or with any other unbaked book on cnx.org: https://cnx.org/contents/jVCgr5SL 

On staging.cnx.org, users are landing on the preface, as demonstrated here: https://staging.cnx.org/contents/jVCgr5SL.

# Acceptance Criteria
- [ ] when a user navigates to a book via the book ID (such as jVCgr5SL or any OpenStax book clicked from the homepage), the user lands on the first module after the preface, regardless of whether the book is baked.
- [ ] that page has a cover and about text, plus a hyperlinked ToC as coded here: https://github.com/Connexions/webview/pull/1886

**Comment by PiotrKozlowski** [comment] 2018-09-07 15:30
Ready for testing.

**Comment by wilkus27** [comment] 2018-09-12 09:37
Verified on katalyst01. 
After clicked on any  book (baked or unbaked) from the homepage user landing on the first module after Preface.

unbaked book:

![prealgebra](https://user-images.githubusercontent.com/40228854/45416260-d080bd80-b67f-11e8-8eaa-268df057d49a.JPG)

baked book:

![concepts](https://user-images.githubusercontent.com/40228854/45416289-e4c4ba80-b67f-11e8-9a4c-651eeff0c20c.JPG)

In parts of books there is a problem with displaying of a cover, but this issue is already resolved on staging.cnx.org by https://github.com/Connexions/webview/pull/1894 and https://github.com/Connexions/webview/issues/1895.

**Comment by wilkus27** [comment] 2018-09-12 16:15
@helenemccarron @PiotrKozlowski After today deployment only unbaked books display correctly. Clicking on baked book from Homepage user is landing in Preface again.

**Comment by PiotrKozlowski** [comment] 2018-09-12 18:30
It's cache or deployment issue. My code is not on the server.
cc @wilkus27 @helenemccarron

**Comment by helenemccarron** [comment] 2018-09-12 19:32
I redeployed and refreshed the cache and believe it is now working as intended. @wilkus27 can you confirm: https://katalyst01.cnx.org/?

**Comment by PiotrKozlowski** [comment] 2018-09-13 07:46
@helenemccarron Your deploy took only 3 minutes and I can't see new files on katalyst server inside `/var/www`, probably server is again out of space.

**Comment by kerwinso** [comment] 2018-09-19 18:47
Addressed in #1953.

**Comment by kerwinso** [comment] 2018-09-19 19:12
Webview@`31d01f7c563ca2c6d60e9629bd6cbfd5e566554e` on qa.cnx.org seems to have fixed the issue: 

- non-baked OpenStax book -- lands on first intro module, not preface: https://qa.cnx.org/contents/caa57dab-41c7-455e-bd6f-f443cda5519c

- baked OS book (UP v.1) -- lands on first intro module, not preface: https://qa.cnx.org/contents/d50f6e32-0fda-46ef-a362-9bd36ca7c97d

- non-OS book (Fast Fourier Transforms) -- lands on first non-preface module:
https://qa.cnx.org/contents/82e6ba6f-b828-42ef-9db1-8de4b448b869

**Closed** 2018-09-21 16:06 UTC
Labels: impact:baked.books, prio:high, question:Helene

**Comment by openstaxalina** [comment] 2018-09-21 19:05
Verified on staging.cnx.org: 
![screen shot 2018-09-21 at 2 05 23 pm](https://user-images.githubusercontent.com/7863733/45901111-6cf53f00-bda7-11e8-9534-797df11521a8.png)

**Comment by openstaxalina** [comment] 2018-09-21 19:10
(Checked all baked books on staging.)
