### ISSUE TITLE
PDF suppresses bullets in lists of Preface, webview does not

### ISSUE THREAD

**Issue by oscryan** [Connexions/webview#1906] opened 2018-09-05 17:16 UTC
<img width="1359" alt="screen shot 2018-09-05 at 12 12 51 pm" src="https://user-images.githubusercontent.com/1895432/45109399-0ca6a200-b105-11e8-856a-d1312d2fb1a7.png">

All these lists are normal bulleted lists in cnxml.

**Comment by openstaxalina** [comment] 2018-09-05 17:27
sorry @oscryan, turns out we did have an issue for this - my mistake!

duplicate of https://github.com/Connexions/webview/issues/1900

Will be resolved in content.  I'll add the AP Bio label to the content-managers issue.

**Closed** 2018-09-13 13:19 UTC
Labels: book:ap.biology
