### ISSUE TITLE
Inconsistent spacing between number and first word of question, in Problems & Exercises

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/webview#1650] opened 2018-06-01 16:23 UTC
@hwangange commented on [Mon May 21 2018](https://github.com/Connexions/cnx-recipes/issues/403)

There are seemingly sporadic instances where no space exists between a question's number and first word. Like question 20 in Ch. 2 Kinematics, Problems & Exercises. 
<img width="852" alt="screen shot 2018-05-21 at 3 54 28 pm" src="https://user-images.githubusercontent.com/12180288/40329472-4497bb1c-5d0f-11e8-8343-a5157eb41879.png">

And question 26 (also Ch. 2).
<img width="737" alt="screen shot 2018-05-21 at 3 54 58 pm" src="https://user-images.githubusercontent.com/12180288/40329499-56f6bbb4-5d0f-11e8-82c1-c9e98ff81c24.png">

And question 59 (also Ch. 2).
<img width="142" alt="screen shot 2018-05-21 at 3 55 27 pm" src="https://user-images.githubusercontent.com/12180288/40329521-6704d888-5d0f-11e8-915b-58089007dc6f.png">

And questions 13-16, Ch.3 Two-Dimensional Kinematics, Conceptual Questions.

<img width="462" alt="screen shot 2018-05-21 at 4 01 16 pm" src="https://user-images.githubusercontent.com/12180288/40329767-3d836528-5d10-11e8-9c13-e6d96a299a16.png">

also in Ch.3 Test Prep, etc.

**Comment by openstaxalina** [comment] 2018-07-09 17:54
This is a duplicate of the issue in cnx-recipes referenced above; closing.

**Comment by openstaxalina** [comment] 2018-07-09 17:55
Actually, we are not sure what repo this should be in.  Helene will investigate.

**Comment by helenemccarron** [comment] 2018-07-17 16:06
This is not a recipe issue, the baked content does not contain extra spaces.

**Comment by helenemccarron** [comment] 2018-07-17 16:32
In the JSON found in https://archive-devb.cnx.org/contents/8d04a686-d5e8-4798-a27d-c608e4d0e187@14.60:OF8r0KAI@14.60/Problems--Exercises.json: 
`<a class=\"os-number\" href=\"/contents/5b05c06e-0cbd-5019-be06-2abd4de9909d#fs-id1770908-solution\">61</a>    <p id=\"import-auto-id1761648\">Using approximate values` 

in the baked HTML found in https://archive-devb.cnx.org/contents/8d04a686-d5e8-4798-a27d-c608e4d0e187@14.60:OF8r0KAI@14.60/Problems--Exercises.html
`<span class="os-number">60</span><p id="import-auto-id2006034">Using approximate values, `

**Comment by helenemccarron** [comment] 2018-07-17 17:09
@openstaxalina this might be a content problem:
```
<exercise id="fs-id1164906424347" type="problems-exercises"><problem id="fs-id1164906424350">    <para id="import-auto-id2173446">(a) A light-rail commuter train accelerates at a rate of
```

**Comment by openstaxalina** [comment] 2018-07-19 19:16
Confirmed these issues are still present in the refreshed content on katalyst01.

I am concerned that the spaces in the content are not semantic and we should not rely on them to add the necessary space after the exercise number.  Would like to discuss at sprint planning.

**Comment by openstaxalina** [comment] 2018-07-20 18:20
I would like to add the equivalent of one character of padding after the number, recognizing that due to the extra spaces in the content, many instances will have the equivalent of two spaces until the content is cleaned up.  I will create a new issue for the content clean up.

**Comment by openstaxalina** [comment] 2018-07-20 21:10
Created issue to fix content here: https://github.com/Connexions/oer.exports/issues/3714

**Comment by uskka** [comment] 2018-07-27 11:03
Works fine. Tested on katalyst01

![screenshot-katalyst01 cnx org-2018 07 27-12-59-22](https://user-images.githubusercontent.com/40228918/43317510-58de6fd6-919d-11e8-823b-d68214effd34.png)

**Closed by uskka** 2018-07-27 11:03 UTC
Labels: book:ap.physics, prio:high
